# Generated by Django 4.2.3 on 2023-07-26 04:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myzloo', '0005_remove_customuser_activation_code_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favorites',
            new_name='myzloo_favorites',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='favorites',
        ),
    ]
