# Generated by Django 4.2.3 on 2023-07-26 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myzloo', '0006_rename_favorites_myzloo_favorites_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorites',
            field=models.ManyToManyField(related_name='favorited_by', to='myzloo.musictrack'),
        ),
    ]
